version: '3.4'

services:

  eshopwcfservice:
    image: eshop/wcfservice:${TAG:-latest}
    build:
      context: ./eShopModernizedWinForms/src/eShopWCFService
      dockerfile: Dockerfile  
    depends_on:
      - sql.data

  eshop.modernized.webforms:
    image: eshop/modernizedwebforms:${TAG:-latest}
    build:
      context: ./eShopModernizedWebFormsSolution/src/eShopModernizedWebForms
      dockerfile: Dockerfile
    depends_on:
      - sql.data      

  eshop.modernized.mvc:
    image: eshop/modernizedmvc:${TAG:-latest}
    build:
      context: ./eShopModernizedMVCSolution/src/eShopModernizedMVC
      dockerfile: Dockerfile
    depends_on:
      - sql.data      
    
  sql.data:
    image: microsoft/mssql-server-windows-developer

