version: '3'

services:
  eshopmodernizedmvc:
    environment:
      - ConnectionString=Server=sql.data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
      - PicBaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP:-10.0.75.1}:5114/items/[0]/pic/
      - UseMockData=False
      - UseCustomizationData=False
    ports:
      - "5114:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

networks:
  default:
    external:
      name: nat
