apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sql-data
spec:
  template:
    metadata:
      labels:
        app: sql-data
        component: sql-data
    spec:
      containers:
      - name: sql-data
        image: microsoft/mssql-server-windows-developer
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Pass@word
      nodeSelector:
       beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sql-data
    component: sql-data
  name: sql-data
spec:
  type: LoadBalancer
  #loadBalancerIP: 52.187.173.125
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: eshop-modernized-mvc
    component: sql-data
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eshop-modernized-mvc
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: eshop-modernized-mvc
    spec:
      containers:
      - name: eshop-modernized-mvc
        image: eshop/modernizedmvc
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: UseMockData
          value: "False"
        - name: UseCustomizationData
          value: "False"
        - name: ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word"
      nodeSelector:
       beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-modernized-mvc
  labels:
    app: eshop-modernized-mvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: eshop-modernized-mvc